### ISSUE TITLE
2017 Conference Coordination

### ISSUE THREAD

**Issue by erickt** [rust-community/team#113]
This ticket is to track organizing 2017 conference coordination as a followup to the [2016 coordination](https://github.com/rust-community/team/issues/25) and our [2016 conference retrospective](https://github.com/rust-community/team/issues/108). See our [notes](https://public.etherpad-mozilla.org/p/rust-2016-conf-retrospective) from the first meeting.

Right now we know of 4 conferences tentatively being planned in 2017:

## Q2 (April - June)

* RustFest - @skade / @badboy / @listochkin
    * April 29-30, Kyiv, Ukraine

## Q3 (July - September)

* RustConf - @aturon / @nikomatsakis
    * August 18-19, Portland, OR, USA
* RustFest - @skade / @badboy / @listochkin
    * September 30-October 1st, Zurich, Switzerland

## Q4 (October - December)

* Rust Belt Rust - @carols10cents
    * October 27-28 Oct, Columbus, OH, USA

Things we need to discuss:

* We need to coordinate on times and locations to avoid conflicts
* How can we improve the diversity of our attendees and speakers
* How can we address accessibility issues
* How can we assist with advertising.
* ...

**Comment by aturon** [comment]
RustConf I think would lean toward keeping the same timeframe as 2016, i.e. early September.

**Comment by Hoverbear** [comment]
We talked about Rustfest being in the spring.

**Comment by aturon** [comment]
Based on venue availability, it's looking like RustConf will likely be either Aug 18-19 or Aug 25-26.

**Comment by spastorino** [comment]
I went to RustConf and RustBeltRust last year. I'm from South America and I will try to give some thoughts trying to represent people flying to a conference from a very far distance :). I spend more or less 20 something hours to arrive.

It would be nice if Rust conferences dates are have a greater distance in time between them. In 2016 they were all pretty close to each other. It's very hard to attend if your travels are costly in terms of money, time, it's also very tiring if there are so close, separating a bit more would be better for people in my situation. 
Also, this maybe applies only for RustConf, it's also better for non US attendees if the city where conferences are held happens in more accessible cities in terms of flights. From time to time the chosen cities are not well connected and if you flight from outside US you need to get on 3 or even 4 flights to arrive.
I know organizing a conference is very hard and some of the things may be impossible to accomplish but at the same time would be very nice of you if those things are considered :).

**Comment by aturon** [comment]
The RustConf 2017 save the date has been announced: http://rustconf.com/, August 18-19

**Comment by erickt** [comment]
If it's possible, it'd be wonderful if we could setup VTC presentations for any speakers that are subject to a travel ban, and make sure we put this in the CfPs so that speakers don't self-filter themselves out of consideration.

**Comment by Hoverbear** [comment]
Would it be possible to consider moving RustConf to Canada due to the recent political climate?

**Comment by aturon** [comment]
Hi @Hoverbear, I was just emailing the RustConf team about this. At the moment, we have a significant deposit on the venue, and venues in Canada come in at a good chunk higher cost. We're trying to weight the best way to use these funds -- for example, we could also consider making the conference more accessible world-wide via livestreaming and chat, for substantially less cost. (It's also not a pure win to move elsewhere, since at least some people currently in the US cannot leave for fear of being denied entry back; but it's not clear how to weigh that).

**Comment by Hoverbear** [comment]
@aturon Indeed this is quite a pickle.

**Comment by skade** [comment]
My solution would as always be to promote quicker setup of more alternatives.

**Comment by skade** [comment]
A little bit of an extension to this. I think we shouldn't rush on this. Times are shit, I agree on that. They don't call for self-flagellation, though.

There's still an ample amount of people in the US that want to visit a conference and on their soil. I'm not very versed in US issues, but I think some people might also not have a passport, which they'd need to travel outside? (correct me if I'm wrong)

Even a conference in Canada is still subject to all kinds of visa issues. Also, Canada is not the cheapest place to travel too, improving the situation to only a few people that would have attended RustConf _and_ have the funds to travel that far.

So, the question is: why would people travel to US east? To meet core community people and a very active community. Have access to all the people that build the thing. It's something other conferences mostly can't replicate.

The solution for this is, in my opinion: decentralise. Instead of growing the conferences in size, we should make sure that we have more of them, around the globe, with enough budget to have a small event for people to socialise and get stuff going. On top of that, make sure we support more of these projects by flying in core personnel that has an easier time traveling. This is a shitty situation, can we solve this by moving outwards?

**Comment by Manishearth** [comment]
Agreed; however I also do think that we should start thinking about this _now_ since it's easier to plan things when there are months to go.


Yeah, Canada, the US, and the UK have pretty horrible visa systems in general. Canada is a bit better, but it's still overall horrible. Schengen visas are _generally_ easier to get, though this is all anecdotal and visa processes have a huge component of chance so I'm not sure.


I don't think we should be motivating this as "retribution" or a boycott, boycotts would work if the tech conf industry was large enough (it isn't) to make a blip and if there was agreement across the tech community to do this (there's not). Rather, it's a practical concern of people who may be excluded. It's tricky -- hold it in the US, and folks from particular countries are excluded. Hold it elsewhere, and US residents (likely the majority audience for RustConf and RBR) with ties to other countries may be excluded. This is compounded by the whole instability of the thing and the fact that we can't really predict what the situation will be like when conf season comes.

I do think decentralizing is a good idea. The existence of RustFest will certainly help, and we should try and get more core folks there.

Kinda hoping for an Asia conf. Probably could help (but not lead) an effort in India if anyone wants to. However, I'm wary of being responsible for giving stomach flu to the entire Rust community 😄 .

**Comment by aturon** [comment]
Thanks, @skade, for your thoughtful analysis, which I personally find quite persuasive.

**Comment by Manishearth** [comment]
https://users.rust-lang.org/t/rustconf-2017-and-the-us-travel-ban/9214

**Comment by skade** [comment]
Better late then never, RustFest 2017/1 happens end of April.

**Comment by carols10cents** [comment]
We've got dates and a venue for Rust Belt Rust - it's going to be Oct 27 + 28 in Columbus, OH!

**Comment by deg4uss3r** [comment]
Are there any dates for a U.K. Rust conference ? I'm willing to help how I can (I'm sure my wife will as well).

**Comment by Manishearth** [comment]
There are only three Rust conferences this year we know of.

- RustConf: Portland, Oregon
- RustFest: Kyiv, Ukraine
- RBR: Columbus, Ohio

There are regular Rust meetups in London, though

**Comment by Manishearth** [comment]
Are you trying to organize one? 😄 We can probably provide some help.

**Comment by Manishearth** [comment]
cc @booyaa

**Comment by deg4uss3r** [comment]
@Manishearth I'd love to but work is kicking my butt and being new to the area I'm at a disadvantage. I would absolutely help out someone who can/will work on it a little more than I can :D

**Comment by Hoverbear** [comment]
@deg4uss3r You're welcome to join us for Rustfest! :) It'll be super fun!

**Comment by deg4uss3r** [comment]
Thanks @Hoverbear :) I'll definitely try to make it to Kyiv but, sadly, something a little closer to home is what I was hoping for this year!

**Comment by dns2utf8** [comment]
Is there a list of all rust confs so we know which dates we should avoid in fall?

**Comment by badboy** [comment]
The comments here would be pretty much the best source. I'll add the known dates to the initial post.

**Comment by Hoverbear** [comment]
Hi folks! Rustfest Kyiv was great and lots of fun. We're happy to announce that Rustfest will be in Zurich next later this year. Stay tuned for dates.

**Comment by igor-krawczuk** [comment]
Is there a need for volunteers for the rustfest@zurich? If so, who should one ping?

**Comment by badboy** [comment]
@igor-krawczuk We're happy to take on help as we need it. We're quite early in the planning so we don't have any definitive needs yet, but feel free to send us a mail to team@rustfest.eu
