### ISSUE TITLE
 2017-02-15 Community Team Meeting

### ISSUE THREAD

**Issue by bstrie** [rust-community/team#129]
Meeting at 5pm UTC on #rust-community on irc.mozilla.org

Last week's agenda: #126 

Propose agenda items below.

**Comment by bstrie** [comment]
* A private place to register corporate contacts for participating in the annual commercial user survey

**Comment by thejpster** [comment]
I have a Raspberry Pi workshop coming up at the Pi Big Birthday Weekend and I'd like to teach 12 Rust newbs how to twiddle LEDs on a Pi using Rust. Could we talk a little about producing workshop material on Rust and how that might be re-used at other events?

**Comment by erickt** [comment]
* underhanded progress
* workshop-a-thon

**Comment by badboy** [comment]
* Mail Rust Event Toulouse, France

**Comment by erickt** [comment]
Results:

* We're going to sync with the core team to officialize a commercial users list, and keep it community/core team private. When it's time to do the next survey, we'll put up a small google survey to collect contact points.
* We pointed @thejpster at the [RustBridge workshop](https://github.com/rust-community/rustbridge/tree/master/workshops materials. He's going to work with the conference organizers to get rust preinstalled to avoid problems installing Rust. He'll also reach out to us to help review his materials before the conference.
* We talked through underhandedness. I'm working on an announcement of the extension, and a sample for overhandedness. We're also need to figure out how if we do have a small number of submissions, is that due to us being robust, or people not trying? So we'll need to have some kind of survey.
* It seems like we're going to lock in on Saturday 3/25 for the RustBridge Workshop-a-thon.
