### ISSUE TITLE
2017-02-22 Meeting

### ISSUE THREAD

**Issue by skade** [rust-community/team#131]
Meeting at 5pm UTC on #rust-community on irc.mozilla.org

Last week's agenda: #129

This week's agenda:

* Invite-only (or hidden) category for tech speakers on URLO https://github.com/rust-community/team/issues/130
* Ways for non-coders to help out Rust. This was a question in the Tech speakers Telegram, maybe someone will join for that.

EIAL (Easy IRC Access Link): https://kiwiirc.com/client/irc.mozilla.org:+6667/#rust-community

**Comment by Manishearth** [comment]
- Fuzz the planet! https://github.com/rust-fuzz/cargo-fuzz and https://github.com/rust-fuzz/libfuzzer-sys

**Comment by sebasmagri** [comment]
I'd like to add a brief status update on multilang discourse tests.

**Comment by thejpster** [comment]
Review https://github.com/thejpster/pi-workshop-rs (before Friday - printing day!)

**Comment by badboy** [comment]
In today's meeting we discussed all of the above points.

* URLO section: approved. Not sure who is technically able to add a section yet. We can discuss details on the issue.
* We are collecting ideas for non-coding people here: https://users.rust-lang.org/t/how-can-non-coders-help-your-rust-project/9598
* cargo-fuzz is out, we should find people to blog about its usage and promote it
* > The `discourse native` way to do it would be with categories and sub categories, this would require to change the setup to display categories instead of topics by default
* please send feedback to @thejpster before Friday (also regarding https://github.com/thejpster/sensehat-rs)

**Comment by badboy** [comment]
[Minutes](https://github.com/rust-community/team/blob/master/meeting-minutes/2017-02-22.txt)
