### ISSUE TITLE
Why Rust website

### ISSUE THREAD

**Issue by erickt** [rust-community/team#186]
@nikomatsakis and @dtolnay had a great idea to build a website that helps explain why people should consider rust, based off of their background. For example:

* web developers might want to hear about how type safety made it easier to write bug free code, or have good performance.
* C++ developers might care more about not having to deal with segfaults, or how Mozilla is integrating WebRender into Firefox.
* CTOs might care about how cheaper it could be to train people programmers to learn Rust rather than C++, and have whitepapers on Rust success stories.

We can crowd source the information by getting people who convinced their companies/projects to use rust and write up their stories.

**Comment by dtolnay** [comment]
Frequently I am talking to a C++ developer or a Ruby developer and I want to give them a link that convinces them why they should pay attention to Rust. That could be a writeup or a video of a talk. I want them to read something or watch something and come away understanding why Rust is worth *them individually* being excited about.

I think the closest thing to "Why Rust" that exists now is Niko's and Aaron's various talks using [this deck](https://www.youtube.com/watch?v=lO1z-7cuRYI), but it fails on both of the following aspects that I think are critical to an ideal solution:

- **Targeted** — The reasons that a C++ developer may care about Rust are totally different from the reasons that a Ruby developer may care about Rust. I imagine breaking this down into specifically targeted pages "as a C++ developer", "as a Ruby developer", "as someone pursuing performance", "as a CEO", "as a cryptographer" and so on.
- **Compact** — A 1-hour talk is the wrong format. Ideally this would be a 10-minute time commitment for someone who knows nothing about Rust. I think that means a single page (per audience) with 5-8 sections. Only some of the sections may resonate with any individual reader so it needs to be easy for them to jump to and read only the sections they care about.

**Comment by booyaa** [comment]
cc @thejpster @aidanhs

**Comment by thejpster** [comment]
I wrote http://blog.cambridgeconsultants.com/wireless-product-development/presentation-mozillas-rust-and-why-we-love-it/ for the embedded C developers at work. Happy to talk about the licence used for the content.

**Comment by erickt** [comment]
Similar project is https://whatcanidoformozilla.org/

**Comment by aidanhs** [comment]
I personally spend more time interested in "what would it look like if I X", rather than "why should I X", so the following are less about "why Rust over C and C++" and more "what should I know about moving from C or C++ to Rust": [gcouprie on vlc and Rust](https://www.youtube.com/watch?v=YTy_JOxGOd4), [carols10cents on zopfli and Rust](https://github.com/carols10cents/rust-out-your-c-talk) and this [comment of mine](https://github.com/ansuz/RIIR/issues/14#issue-218357536) (plus related [talk](https://skillsmatter.com/meetups/9837-rewrite-it-in-rust-some-experiences-in-journeys-from-c-and-c-plus-plus)). I also like the questions on urlo where the answer is "you can't do that because Rust is saving you" e.g. [here](https://users.rust-lang.org/t/cannot-borrow-as-mutable-more-than-once-at-a-time/8922).

**Comment by sebasmagri** [comment]
I could help defining the graph for Web Developers and people coming from high level languages for why the could find Rust being useful and better for their work... Having answered a bunch of (repeated) questions about this at the Mexico City meetup it would be nice if I could just print a small card with a QR code pointing to this resource and then clarify on the details.

**Comment by nikomatsakis** [comment]
Hello all! @alevy and @joshtriplett and I were talking about this at RustConf. I think a lot of what we said is already in this thread, but I [wrote up a gist with some notes](https://gist.github.com/nikomatsakis/eb895969b4de4e178f7a92b4bd26a8dc). This could serve, I was thinking, as the kernel of a repo that we can send to people who are looking for tips on how to advocate for Rust. Or perhaps it would be better to fold it in to a more general "why rust" website -- but I'm just looking for easy ways to get something "up and going" very quickly (hence the "repository of markdown files" format). =)

**Comment by nikomatsakis** [comment]
Also, this Why Rust talk from intorust.com might be of interest:

http://intorust.com/tutorial/why-rust/

It is far from perfect, but it outlines some concrete scenarios:

- Integrating Rust into Ruby to make it faster (and nicer than using C).
- Parallelizing with Rayon (and without bugs and data-races).

**Comment by dtolnay** [comment]
I began brainstorming some points for the C++ audience. These are drawn from my own frequent frustrations. Will need to be fleshed out further and edited for tone (Rust is fast, reliable, productive, not C++ is bad). Also these are fairly low-level gripes, which may not be the most impactful direction to take in a "Why Rust" document. I will try to come up with some big-picture items to replace these, generalize these, or at least balance these out.

---

### Templates are fully type-checked independent of any specific instantiation

In a C++ template, code depending on a type parameter is not checked until the template is instantiated by the caller. This imposes a large maintenance burden on templates exposed in the public API of a library. It is possible for reasonable-looking modifications to the body of a template (without changing its signature) to break call sites, and the compiler is powerless to catch this without knowing all the concrete type parameters the callers will want to use.

There are techniques to mitigate this with [`std::enable_if`] and the upcoming [Concepts] feature, but neither gets us to a point where a template can be type-checked in isolation.

[`std::enable_if`]: http://en.cppreference.com/w/cpp/types/enable_if
[Concepts]: https://en.wikipedia.org/wiki/Concepts_(C%2B%2B)
[dialect]: https://github.com/llvm-mirror/libcxx/blob/487562fc64b4a950f95b65d4d8f46e8246f42e62/include/string#L2421-L2470

```cpp
template<typename T>
concept bool Example = requires(T a) {
  { a.example() } -> void;
};

template<typename T>
void f(T &&a) requires Example<T> {
  a.example();

  // The name of the function contains a typo but the compiler cannot catch it.
  a.exampel();

  // This may coincidentally work for all of the types T used in our test suite,
  // but not when the user tries to instantiate with one of their types.
  a += "example";
}
```

As a workaround, template libraries that need to be robust to unusual type parameters are written in a special [dialect] of C++ to minimize breakage. For example they use [`std::addressof`] instead of `&`, in case some call site uses a type parameter that overrides `&`.

[`std::addressof`]: http://en.cppreference.com/w/cpp/memory/addressof

#### Why Rust?

In contrast, generics in Rust fully type-checked. The compiler can look at a generic function in isolation (without needing to know about any callers) and say for sure whether it is correct or incorrect. If it is correct, that means call sites will compile successfully if and only if they satisfy all of the trait bounds in the signature of the generic function.

By extension, this gives us the ability to improve the implementation of a generic function without fear. As long as the signature does not change, all call sites are guaranteed to continue to compile.

```rust
trait Example {
    fn example(&self);
}

fn f<T: Example>(a: T) {
    a.example();

    // Does not compile, even if `f` is never instantiated within this library.
    a.exampel();

    // Does not compile. Nothing in the signature of `f` gives us the right to
    // do this.
    a += "example";
}
```

---

### First-class references

A reference in C++ makes a statement about ownership. It means the code holding the reference is not supposed to delete the data or hold on to the reference beyond when someone else may have deleted the data.

This is a useful and commonly applicable contract. Unfortunately references can be confusing to work with in some contexts. For example, making a vector of references results in 300 lines of template errors (a symptom of the previous section).

```cpp
std::vector<const std::string &> v;
```

The correct workaround in this case would be to use a [`reference_wrapper`], but at this point the type gets big enough that clarity begins to suffer.

[`reference_wrapper`]: http://en.cppreference.com/w/cpp/utility/functional/reference_wrapper

```cpp
std::vector<std::reference_wrapper<const std::string>> v;
```

#### Why Rust?

In Rust, a reference is a first-class type and generally behaves just like any other type. Want a vector of references? No problem!

```rust
let v: Vec<&str>;
```

**Comment by dtolnay** [comment]
[*C++dev here. Sell me on Rust?*](https://www.reddit.com/r/rust/comments/6xk3ja/cdev_here_sell_me_on_rust/)

**Comment by nikomatsakis** [comment]
@dtolnay sorry, just saw that comment -- I think those are the right sort of thing! Quite specific, speaks to everyday experience. I always overlook the "typecheck before instantiation" thing.

**Comment by skade** [comment]
I'd say this is superceded by... the website :).
