### ISSUE TITLE
observer/guest initiative and policy

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-community/team#200]
several of our recent meetings have had guests attend, which i think we've all really enjoyed. as we move into 2018 i would love to see more of this happen. i think that formalizing a policy for inviting guests, or people to be observers would help make this happen more often :)

i have several ideas but i will let the conversation start- as i'm excited to hear what ya'll think

cc @booyaa @erickt from meeting 29 dec 2017

**Comment by Manishearth** [comment]
In the past we've had lots of folks informally drop in to discussions and that worked pretty well.

But in the new meeting format there's more focus so this probably won't play out as well. Just mentioning something in the agenda seems fine?

**Comment by skade** [comment]
So, the original idea (but never put into policy) was to keep the meetings open and documented _by default_. Also, we would anyone with interest in a topic to join in. This doesn't mean that we can't handle subjects in a closed meeting when we find it appropriate.

As most forms of "no policy", this hasn't worked as intended, mostly the meetings were to ourselves.

I'd happily help and support drafting a new policy.

**Comment by Manishearth** [comment]
Here's the strawman proposal:

Meetings continue to be open by default. Folks can drop by and take part in discussions if they wish, however they may be asked to table it till later in case it's not the topic being discussed. This puts them at the same level as team members during a team meeting, which is fine imo. We can of course tweak this on a per case basis; if we're running out of time and need team feedback we can ask them to table it till later even if on topic.

If someone not from the team wishes to lead or participate in an agenda item, they may comment on the agenda issue or ask a team member to set it up for them. We try to give priority to agenda items involving such guests, since they may not be able to make it for other meetings.

If _you_ have an agenda item you're leading in a meeting, a couple days before the meeting please be sure to consider if there are non-team members you'd want to be there, and invite them if so. Mention that they've been invited in that issue.

**Comment by Manishearth** [comment]
(unclear if this is the kind of proposal you wanted, please let me know if the proposal is addressing the wrong thing 😄 )

**Comment by ashleygwilliams** [comment]
for posterity (i've shared in private convo and IRC): please make this a PR! i think it looks like a great starting point for dicussion :) thanks so much

**Comment by Manishearth** [comment]
https://github.com/rust-community/team/pull/207
