### ISSUE TITLE
all hands: community team session planning

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-community/team#224]
there will be an all hands for rust in berlin during the last week of march. i would like to have a few meetings for community topics as many of us will be together in person for the first time in a while. let's use this issue to brainstorm what the community team's goals for the all hands are, and what topics we'd like to discuss.

i'd like to have 1-2 goals, with 2-4 sessions at the most (if possible). it's gonna be a busy week!

**Comment by bstrie** [comment]
One of the things that's been on my mind recently has been recognizing contributors better, which pulls in a variety of topics: most pertinently in finding ways to recognize non-technical contributors, but also in expanding the recognized variety of technical contributors (which today pretty much just means "you made a git commit", which leaves out other technical roles like PR reviewers), plus friends of tree, thanks.rlo, and our practice of no longer putting contributor names in the release notes.

I have a variety of proposals for the above, but I'd also like to have an open discussion with members from all the Rust teams regarding what sort of contributions they and their teammates typically make, and how we can better recognize their own contributions and those of the community members they work with, especially in an automated way that doesn't e.g. increase the burden on people writing the release announcements. If this sort of cross-team presentation/discussion is what you're looking for for the all-hands, then I'll immediately take on the long-anticipated overhaul of thanks.rlo in order to have a practical demo.

**Comment by ashleygwilliams** [comment]
based on my work with @aturon so far it sounds like we'll have the option to have about 2 large 2 hr sessions at the allhands. my main goal for us is to really push forward some of the initiatives we've already started.

i think one session should be devoted to the events team, primarily because many of the team members will be at the event. i think it would be great to ship https://github.com/rust-community/events-team/issues/8 and https://github.com/rust-community/events-team/issues/7

as for the other session, i'm not entirely sure. there is definitely some really great work to be done on rustbridge tho i don't know how many attendees are interested in working on that.

would love to hear your thoughts!

**Comment by skade** [comment]
From the events side, I definitely have a couple of things I'm interested in:

They split into two things:

Rust events, run by Rustaceans (think RustFest):
* What are our resources (speakers, money, free places, funding, promotion)?
* How can we encourage people to run events without strong ties to the project? (Because ties mean effort)
* How can we improve standards at events?

General events, run by others (think OSCON, etc.):
* What are our resources (speakers, money, free places, funding, promotion)?
* Can we involve community members, companies instead doing work on our own?
* How much "project" involvement is even necessary?

In general, it comes down to the old problem: we know a lot and have a lot of contacts, but how can we make sure that this doesn't make us the single point of failure?

**Comment by ashleygwilliams** [comment]
@skade i think using a second session to discuss those questions would be a great idea, i know that i have info on swag and design budget that i haven't sorted and that additionally how we spend money on events is  bit disorganized and would benefit us to sort (also will benefit the moz reps crew as well, i've talked to them about this a bit)

so that's 2 events sessions- @bstrie i think your idea is good but i would like to see if we can't attach that project to a subteam and align it with our goals for the year?

**Comment by ashleygwilliams** [comment]
oh also @bstrie i would def reach out to @steveklabnik to see what his current thinking on thanks is. coordinating with him on that seems like a good idea

**Comment by steveklabnik** [comment]
https://github.com/rust-lang-nursery/thanks/pull/99#issuecomment-357485556 <-

**Comment by mattgathu** [comment]
> as for the other session, i'm not entirely sure. there is definitely some really great work to be done on rustbridge tho i don't know how many attendees are interested in working on that.

I will not be at the sessions but I would really encourage discussions about **rustbridge**.

I'm particularly interested in how the community team can empower upcoming rust communities through rustbridge. I had been looking forward to the **teachers workshop** (_sad it hasn't happen yet_) and it would be great if the team came up with something concrete about it for 2018.

**Comment by bstrie** [comment]
@ashleygwilliams re: contributors and thanks, I'm not sure that this falls under the purview of any existing subteam (and I don't think it'd be worth the trouble to create one). I also don't think that this really falls under the purview of any other Rust team at all, which is part of the problem in the first place: it's nobody's particular responsibility, so it doesn't get ever get done! :)

I also don't think that my proposal needs an entire 2-hour slot. I don't see it being more than 30-45 minutes, including time for open discussion. If the all-hands has some flexible unconference time that people can have spontaneous panels in, then that'd be fine. Does it? Alternatively, we could split up our slots into many panels (which sort of sounds like what the events subteam is doing already).

**Comment by skade** [comment]
@bstrie It will have that and I'll be in charge of that :).

**Comment by ashleygwilliams** [comment]
@bstrie yeah, it sounds like your session would be best coordinated in the "community space" time, and i know that @skade is organizing a bit of an unconference type structure for that so i would circle up with him :)
