### ISSUE TITLE
[AGENDA]: 27 June 2018

### ISSUE THREAD

**Issue by booyaa** [rust-community/team#237]
5-5:30pm UTC on the `community-team\general` in Discord (https://discordapp.com/channels/442252698964721669/443773747350994945) please ask @booyaa for invites if you don't haven't joined Discord before.

- housekeeping (@booyaa - 5min)
  - comm team leadership distribution update
- survey (@jonathandturner - 2min)
  - survey team had kickoff meeting.
  - if you want to join, ping me
- rustbridge (@oe)
  - nothing interesting
- switchboard (@Manishearth - 3min)
  - updates on the team (3min)
- events (@skade - 2min)
  - updates about the work hour on sunday
  - events list
- content (@booyaa - 2min)
  - Communication guidelines for team
  - Investigate Content-o-Tron being part of a Summer of Code program
- l10n (@sebasmagri - 5min)
  - First meeting held. Will be meeting on an as-needed basis.
  - Priorities set up to:
    - L10n community census
    - Website l10n
    - rustc diagnostics i18n
    - Coordinate TRPL translations

**Comment by badboy** [comment]
- housekeeping
  - [Add meeting facillitation policy](https://github.com/rust-community/team/pull/238). Feedback welcome.
- survey
  - Ask @jonathandturner if you want to be involved
- switchboard 
  - with production WG switchboard is less useful. most things are covered elsewhere. "connecting people" is done passively.
  - spinning the team down
  - jturner: what is this passive work?
  - manish: pulse of community
    - answering mails, giving calendar access
- events 
  - skipped team meeting, work hour on sunday instead
  - worked on [foss-events-planner](https://github.com/rust-community/foss-events-planner/)
  - List of all larger events available, private because contact data
  - Non-contact data will soon be made public
- content
  - [Communication guidelines](https://github.com/rust-community/content-team/pull/33). Feedback welcome. Will be merged by end of this week
  - Content-o-Tron as part of a Summer of Code: update next team meeting
    - [join meeting next week](https://github.com/rust-community/content-team#meeting-times)
- l10n
  - Manish + sebasmagri met to define priorities
  - the idea with the census is to form working groups for each language with liasons that we can loop in to check progress
  - figure out pending work in specific projects
  - translate community survey and add additional community questions
    - cc @skade
  - fluent/fluent-rs for website & compiler translations
  - book not to be considered: "just write a different book"
  - rustdoc not to be considered right now
- followups:
  - Meeting on discord: worked! typing notifications help
  - missed final countdown at beginning
    - @erickt [saved the day](https://www.youtube.com/watch?v=zraN5zM0VW8)
  - signup for facilitating/notetaking will follow (google doc)
