### ISSUE TITLE
Community Team Meeting Agenda December 25th, 2019 & January 22nd, 2020

### ISSUE THREAD

**Issue by technetos** [rust-community/team#277]
# Community Team Meeting
> December 25th, 2019 & January 22nd, 2020

- is there a deadline for moving repos to rust-lang? @JohnTitor

**Comment by Zexbe** [comment]
Possible Agenda Item
---
Rename the channel content to content-team on discord.

Reason
---
New people will tend to go to the content channel, because it looks like a landing page.
The new people who chat on it, are told not to chat on it, then eventually new things get posted, and the warnings get buried, and the process repeats.
This is a bad experience for new users, who see arguing, or get into an argument the first time they enter the discord, and sometimes disruptive to the content team.

**Comment by flaki** [comment]
# Agenda item
I would like to discuss our intent to create an (at least initially) invite-only channel on the Rust Zulip for Rust event and conference organizers. This is initially for avoiding clashes between the event dates, with other potentially useful future usecases.

cc @skade @badboy

**Comment by vertexclique** [comment]
My proposal is translators medium.
Iirc, we haven't discussed the translators medium topic last time.
Here is the link for it:
https://github.com/rust-community/team/issues/275#issuecomment-559146482
