### ISSUE TITLE
Community Team Meeting Agenda February 26, 2020

### ISSUE THREAD

**Issue by technetos** [rust-community/team#278]
# Community Team Meeting February 26, 2020

@XAMPPRocky, @Manishearth - Clarifying maintainership of the rust-unofficial org
+ At one point rust-unofficial was org set up by the community team for projects that they weren't comfortable having under rust-lang, currently there's three main projects that still maintained here. patterns a repo about Rust patterns, too-many-lists the book about learning Rust with "Too Many Linked Lists", and awesome-rust the list of different rust resources and tools.

It seems like it would be easiest if we said this isn't a community team project but one made by some ex and some current community members, essentially punting the maintainership entirely onto the current admins.

**Comment by Manishearth** [comment]
> set up by the community team for projects that they weren't comfortable having under rust-lang

This isn't true: The org was set up for important-ish projects that were maintained by other folks that they weren't able to maintain anymore and wanted to hand off. It's kind of a holding ground for such projects to provide a basic maintainership backstop, and ideally grow them back into projects that others run.

Some of these projects could very well exist under rust-lang: too-many-lists probably should. awesome-rust definitely should not and is one of the reasons we went out of our way to clarify the org as unofficial crates.

**Comment by XAMPPRocky** [comment]
Sorry yes, I was only really thinking about `awesome-rust` when I wrote that. Thanks for putting the extra context here.

**Comment by flaki** [comment]
### Agenda Item
*A follow-up for [last month's agenda item](https://github.com/rust-community/team/issues/277#issuecomment-577277351)*

From **pickfire#5032** on `#community-team` on Discord:
> If we could add like a list of people doing rust community events around the world in one place, so we can easily find other rust meetups/conferences organizers?
> [...]
> Yes, but it does not mention like which place have the event, google calendar tracks time. So, I suggest to track place and people.

We have something similar in the works on Zulip. It's the start of building what **pickfire** is asking for, basically giving (initially) conference organizers a place to sync up on their plans so e.g. two confs being are aware of each others' dates and making sure their dates are not clashing (if it can be avoided), even before they go public on the dates.

It could also contribute to coalescing confs in a calendar-y fashion, be that [a blogpost](https://blog.rust-lang.org/2020/01/31/conf-lineup.html) or timetill.rs Et Al. But we want to start small.

We have started setting up a private thread on the [Rust Zulip](https://rust-lang.zulipchat.com/) with the help of @nikomatsakis.

*PS: this is also a way towards (or maybe another approach for) the internal event calendar discussed in #262*

> Edit: 2020.02.27: fixed the issue number to point to the correct issue filed about a frontend for ingensting values into the events calendar

**Comment by Manishearth** [comment]
@flaki note that there is already an internal spreadsheet and mailing list of meetup organizers. We could potentially turn the spreadsheet into a page somewhere.

**Comment by XAMPPRocky** [comment]
As an aside if you have resources that are protected to be internal only, and want to easily document and share them. A lot of other teams put links to them on their team [Forge](https://forge.rust-lang.org/community/index.html) page, so that's easy to find for other members.

**Comment by flaki** [comment]
@Manishearth the current idea with the Zulip is to start small, and reserve it for larger events for the time being, while we gather info on what kind of experiences and interactions are useful in this space and figure out the next steps on where to go from there.

I expect that the use cases of conference-organizers are going to be different from those of meetup/community organizers in general, so creating a public (and more general) channel is on the table, to complement the private channel reserved for a smaller group of event leads from large events.

Compiling a list of contacts for either, though, would be a good next step (and this is, in fact, how we started the preparations for the private channel -- by collecting a list of events and contacts to their teams/main organizer or team leads).

**Comment by skade** [comment]
Agenda items from me:

* Policy of the rustvideos YT account around non-talk videos. What do we want to feature, and to which goal?
* Team Roster cleanup
* Move of repositories into `rust-lang`

**Comment by pickfire** [comment]
Similarly, some rust meetup groups from a few countries in Asia such as Singapore, Taiwan (talks probably in Mandarin), Hong Kong (talks probably in Cantonese) and not sure if China have Rust Meetup or event Japan from what I know does not seemed to be aware that they could post their events on rust youtube channel or on the community calendar (or sometimes they do post). Based on what I know:

- Taiwan
  - group in telegram in traditional chinese - rust.tw
  - there is a mozilla community space there
  - talks probably in Mandarin
  - video not always recorded (I think they want to get access to rust youtube channel but didn't request)
  - post to rust calendar
- Hong Kong
  - not sure where their group is discussing
  - IIRC their rust meetup is mixed with other meetup (functional group)
  - IIRC some talks recorded
  - talks probably in Cantonese or English (I never seen one)
  - posted in rust calendar (last post 2019 Jan)
- China
  - group in telegram in simplified chinese - Rust 众
  - not sure if they even have meetups
  - if they have, probably in Mandarin
  - one rust meetup was posted in calendar in hangzhou
  - understandable for not posting due to the great firewall
- Singapore
  - not sure where their group is
  - talks in English
  - video posted to engineers.sg youtube channel
  - does not post to rust calendar (not sure about their local calendar)
- Japan
  - talks probably in Japanese
  - not sure if talks recorded
  - talks not posted in rust youtube channel
  - slack group in rust-jp.rs in japanese (they general channel is quite interesting, a lot of newcomers keep introducing themselves in a daily basis, I never seen this in other groups)
  - post in rust calendar
- Malaysia
  - where I am from
  - main channel in telegram merged with (golang and *-lang), there is also a facebook group, mainly english
  - talks in English, sometimes a little bit of Mandarin or Malay
  - video posted to engineers.my youtube channel and cross-posted to rust youtube channel
  - post to rust calendar (and local devkami calendar)

Just wondering how should rust youtube channel and calendar can be more discoverable to groups that does not communicate in full english, how could they find out about the youtube channel and calendar? From what I know, I only discovered about the youtube channel and calendar through this-week-in-rust, otherwise I would not have known we have these things.

**Comment by vertexclique** [comment]
Renaming `project-localization` to `community-localization` https://github.com/rust-lang/team/blob/master/teams/community-localization.toml#L21

That adds consistency for the localization.

**Comment by Manishearth** [comment]
For rust-unofficial, the rough decision was:

 - move too-many-lists into rust-lang
 - for everything else keep it in rust-unofficial; it is no longer a community team project. Maybe attempt to grow it independently.

**Comment by pickfire** [comment]
How about patterns and awesome-rust?

**Comment by Manishearth** [comment]
They stay in rust-unofficial, as brought up earlier we don't want them in rust-lang due to issues with semblances of officialness

**Comment by pickfire** [comment]
How about https://github.com/ralfbiedert/cheats.rs/? Should it get into rust-lang or even rust-unofficial since most of the stuff there are quite useful?

**Comment by Manishearth** [comment]
No? That's maintained. rust-unofficial is a legacy venue for useful resources that people handed off maintainership of to the community team. It's not currently accepting more projects.

**Comment by XAMPPRocky** [comment]
> Policy of the rustvideos YT account around non-talk videos. What do we want to feature, and to which goal?

@skade Another interesting data point on this, that I found when I went through the feedback on the Rust survey. A common request submitted was for there to be more Rust video content.
