### ISSUE TITLE
Community Team Meeting Agenda April 22, 2020

### ISSUE THREAD

**Issue by JohnTitor** [rust-community/team#280]
# Community Team Meeting Agenda April 22, 2020
- The future of RustBridge team (cc: rust-lang/team#318)
- Community Engineer Position at Mozilla (@skade, @nikomatsakis)
- Online meetups and conferences (@skade)

**Comment by skade** [comment]
Added "Community Engineer Position at Mozilla". There's a position open and I'd like to give some space to talk about questions around this :), as this person will be working with us. I'd like to make this moment the best one for this person and us.

**Comment by skade** [comment]
Added "Online meetups and conferences". With everything moving online, we should check out how to help there. And with RustConf cancelled, we'd have to update our conference info in some way.

**Comment by technetos** [comment]
# Action Items

## Covid19
All the conferences and meetups are cancelled or remote only.  We would like to gather a list of meetups (and conferences too?) that are remote only so that we can expand the reach of the meetups as much as possible.  
+ Make a gh issue for people to comment on with their meetup info.  
+ Make a blog post describing the situation and our goal.  
+ Spread the blog post on reddit, twitter, etc

## Open Rust Team position
Reach out to @nikomatsakis for more information if you are interested.  

## Carry over
We didnt really cover the future of rustbridge, move it onto next months agenda
