### ISSUE TITLE
2016-05-18 Meeting Agenda

### ISSUE THREAD

**Issue by skade** [rust-community/team#29]
No sure what the agenda is :).

I cannot attend (Birthday party of some programming language), so I will send you a notice about my ongoing things later tonight.

**Comment by skade** [comment]
Here's my points:

* we forgot to ask if we could contact people with offers in the survey (e.g. selected a conference place where we actually run a conference)
* RustBridge: we have 5 people continents interested in running something. Relationship to Mozilla should be clarified _fast_.
* RustBridge 2: will a RustBridge team be a seperate team listed on the rust site?
* RustBridge 3: will RustBridge live on rustbridge.tld or bridge.rust-lang.org (latter making clear the endorsement, but how do we manage the setup?)
* I reopened a contact with someone doing embedded development with Rust. Would a core team phone call about embedded be worthwhile again?

**Comment by carols10cents** [comment]
- Can we get #rust-community logging on the web? botbot or logbot or something?

**Comment by carols10cents** [comment]
> * we forgot to ask if we could contact people with offers in the survey (e.g. selected a conference place where we actually run a conference)

Also important imo are the people who are in the same location and are interested in a meetup-- we didn't ask permission if we could get them in contact with each other, but we could potentially help more meetups get started if we do! We added this to the [issue for next year](https://github.com/rust-community/team/issues/28) - for this year, since they gave *us* permission to contact *them*, I think we'll just need to contact them to ask for more permissions. We're going to take action on this when the survey has been closed.

**Comment by carols10cents** [comment]
We decided to create a repo for central rustbridge coordination/collaboration/discussion - https://github.com/rust-community/rustbridge I've also made a rust-community team with access to that repo, please let me know the github usernames of other people who should be added or add them yourself, I've added @skade, @Manishearth, and @johannhof so far! https://github.com/orgs/rust-community/teams/rustbridge

**Comment by Manishearth** [comment]
> RustBridge: we have 5 people continents interested in running something. Relationship to Mozilla should be clarified fast.

Broadly, Mozilla will provide funding, but not be directly involved. Core will be involved in the same capacity community is.
