### ISSUE TITLE
Plan for our inaugural team meeting

### ISSUE THREAD

**Issue by erickt** [rust-community/team#3]
Current thinking is every other Wednesday at 5pm UTC == 10am PST == 6pm Berlin == 10:30pm Mumbai. Will this work for everyone? I'm also thinking that we try hosting our meetings through the irc #rust-community channel to improve our transparency and ease of community members participating. If it turns out to be too noisy, we can always switch to a different channel.

Please append any agenda items to this ticket if you think of anything you want to discuss.

**Comment by skade** [comment]
IRC sounds good. I'm A+ towards 6pm on Wednesdays: that's doable for me after work and on days where there is Rust Berlin, I can just go to the venue an hour early.

**Comment by brson** [comment]
Works for me.

**Comment by erickt** [comment]
Also, since I am now realizing I wasn't clear about this, does this Wednesday, March 23rd work for the meeting? I *think* that's the same Wednesday across all our timezones.

**Comment by bstrie** [comment]
All for it. Eric, I think you have my phone number, so call me if I happen to forget to wake up. :)

**Comment by erickt** [comment]
@bstrie: will do!

Things for the agenda:

* What should we have on our website?
* How should we divide content between https://github.com/rust-community/team and https://users.rust-lang.org/c/community?
* How can we support the upcoming conferences?
* How do we start a mentorship program?
* Outreach projects
 * [Identifying groups](https://users.rust-lang.org/t/identifying-organizations-for-outreach/5088)

**Comment by skade** [comment]
So, in the interest of getting things moving: is tomorrow? I'd prefer getting a rhythm going soon rather then painfully trying to get all stars aligned for the first one.

**Comment by Manishearth** [comment]
Tomorrow sgtm

**Comment by erickt** [comment]
Sounds like we have a quorum, so let's lock in tomorrow. @steveklabnik, I hope you can also make it!

**Comment by Manishearth** [comment]
Could you create a google calendar event?

**Comment by erickt** [comment]
@manishearth: done! It's on the community calendar, which felt appropriate

**Comment by erickt** [comment]
Agenda: * how can we raise awareness of speakers talking at conferences and other significant events?

**Comment by erickt** [comment]
How can we measure if we are being effective at organizing and engaging our community?

We should run a survey. What do we want to ask?
- what region are you in
- what kinds of projects are you interested in working on
- what is your technical experience?
- do you want a mentor or want to be a mentor (if we start some mentorship project)?
- do you have a meetup, and what is it doing well and what could it do better?
- what are technical pain points you are running into?
- what could the community be doing better?

**Comment by jdm** [comment]
I would want clear definitions of "mentor" for that question if it were included.

**Comment by aturon** [comment]
Some general questions that have been on my mind for a while:

**What can we do to foster and gain more visibility into Rust communities outside the English-speaking world?**

- We've made some initial steps toward supporting translations of the web site and ultimately the book
- Are there other investments we can make?

**Can we build community efforts around not just the main Rust distro, but also the ecosystem?**

- How does that fit in to our infrastructure? 
- How can we make such an effort sustainable?

**What are meaningful steps we can take toward inclusiveness and diversity?**

We have a welcoming community, but haven't been taking coordinated, *proactive* steps on this front. 

Some ideas:
  - Targeted mentoring and support
  - Targeted outreach (e.g. visiting groups like PyLadies to both listen, and to talk about Rust)
  - Targeted financial support for attending events or otherwise participating in the Rust community (like with RustCamp, but more systematic)
 
Note: a good goal here is increased diversity in leadership.

I also have a question specifically from the core team perspective:

**How can the core team best support community team efforts? We have leadership stature that could be useful.**

Right now, our community work is focused on: 

-  serving the online/internals community
  - running subteams
  - shepherding RFCs
  - mentoring/working with community on core technical contributions
- messaging Rust's vision (blog posts etc)
- giving talks at conferences, research labs, companies
- visiting or talking with production users
- helping run metups
- developing tutorials and other slide decks. 

But this work is largely done separately from community team. Maybe some of this work can be made more visible, or done with more coordination with broader community efforts. And maybe there are things that the core team is uniquely positioned to do, but aren't doing yet.
