### ISSUE TITLE
bors-as-a-service

### ISSUE THREAD

**Issue by erickt** [rust-community/team#41]
[homu.io](http://homu.io/) seems to be unmaintained, and unfortunately @barosl doesn't appear to be responding to [requests](https://github.com/barosl/homu/issues/151). Since this is an important project for our community, I suggest we start investigating building a clone of the service.

**Comment by edunham** [comment]
Servo and @barosl have [agreed](https://github.com/barosl/homu/issues/122) to keep active development and new Homu features in the [Servo fork](https://github.com/servo/homu), while intermittently backporting some features to the original fork when Barosl has time to review them. I don't believe that the web frontend currently used by homu.io, or the additional test suite that Barosl uses to test Homu changes, are publicly available anywhere right now.

Homu is [MIT-licensed](https://github.com/barosl/homu/blob/master/LICENSE), so we're good to run our own site based on him and sell his services in the future if we want to.

**Comment by skade** [comment]
@edunham Is there a particular reason why homu.io should remain closed? Implementing and running our own site seems like doubled effort.

In any case, what would be the next investigation step?

**Comment by edunham** [comment]
@skade, the next step is to get in touch with @barosl and see whether the source of homu.io can be published for us to use. Alternately (if you can't get ahold of Barosl in a timely manner, or the homu.io source can't be published for any reason), architect a design for bors.io workflow and recruit community members to implement it :)

**Comment by Manishearth** [comment]
Homu already has an admin API in its source for adding repos and whatnot. We can probably write a thin UI around it and perhaps a user UI for adding their own repos.

**Comment by nathanhammond** [comment]
Hello from the Ember community! (Puts on official Ember community representative hat.) We in Ember land know and love @homu. However, it appears that time has again gotten in the way of open source (normal) and homu is down.

Rather than Rust and Ember both going through the efforts of setting up our own landing bots and maintaining them we'd love to partner on building a solution which we can share–reducing the amount of effort our communities individually have to invest into tooling which benefit our end goals of building quality software only transitively.

Other things worth noting:
- Our community has a strong code of conduct matching the Rust project's.
- We happen to know a few people who are good at building user interfaces.

The main thing here is to build a team around the project so that it is sustainable. Because open source time availability happens. Is this an effort you would like to plan and share together? (We don't have a point person identified for this effort yet but if it's something we wish to undertake that person will materialize.)

/cc @wycats @Turbo87 @stefanpenner

**Comment by Manishearth** [comment]
So, Servo (mostly, me) is semi-maintaining a homu fork at https://github.com/servo/homu. We can work on the code there.

As for deployments, Servo's deployment isn't set up to allow for plug-and-play additions, but I'd love to help. I am terrible at UIs but I understand the homu code and can otherwise contribute.

**Comment by locks** [comment]
Hallo :) I'm from the Ember.js Learning and we've been taking on some of the infrastructure work, so I'd be very interest in helping this along.
I suggest opening an IRC channel in the Mozilla network for homu, so we can coordinate. What do you think?

**Comment by skade** [comment]
@locks  Go ahead and see if it sticks. We're usually not too picky on how the syncing between people works, as long as it works :).

**Comment by erickt** [comment]
@nathanhammond: that's wonderful! We'd love to collaborate on this, and really appreciate the offer of help with the UI. It'll really help to get this up and running.

@locks: Great, and good idea! I've created `#bors` on irc.mozilla.org for us to communicate on.

@reem: Would you and the Iron team be interested in helping with the backend?

@edunham: Would this be something that could be run under the Mozilla accounts, or should we just start our own thing for now? I'm fine paying for hosting for now though. I'm sure we could do fine with the Heroku Free or $7-a-month hobby for this.

In other news, I've secured us the dns name bors.io for this endeavor once we have something to put online.

**Comment by Manishearth** [comment]
We're already all in #homu 😄 

I think this could be run under Mozilla; not sure. I and @frewscxv can help with the backend, and @cgwalters / @ignatenkobrain may want to join too.

**Comment by oblitum** [comment]
Do you folks are already in conversation about https://github.com/barosl/homu/issues/119. I really wish homu/bors to get more love in FOSS as well as in any working place, supporting other services would be nice.

**Comment by erickt** [comment]
@oblitum: we are not at that point, but that seems like a wonderful idea to me. We'd be developing this out in the open, so I imagine we'd be more than happy to take contributions to add support for these sorts of things.

**Comment by erickt** [comment]
We've started a proper fork, so lets move the discussion of this over to https://github.com/rust-community/bors!
