### ISSUE TITLE
Set up a few rules around #rust-community

### ISSUE THREAD

**Issue by skade** [rust-community/team#43]
Today, a document intended as a draft was leaked to Hacker News. This was obviously a mistake, someone took the document for a finished doc and published it.

While I value transparency and open processes, the community team and the Rust project still makes plans and sets release dates on things.

For that reason, we should set up a few rules around #rust-community, among them that _any_ link published there is not meant for publishing except with consent by some the community team member in charge of the topic. Also, repeated offenses against this should mean banning from the channel. (FWIW: I don't expect that to happen, most of this stuff happens by accident.)

Any other things we should clarify?

**Comment by bstrie** [comment]
I'm not opposed to this, but note that this is unenforceable in general. We don't prevent people from joining the channel in any way, and if a document is leaked we have no way of knowing who leaked it unless they themselves step forward.

This would be a nice good-faith community guideline, but it doesn't preclude the need for access controls on sensitive documents.

**Comment by skade** [comment]
I don't agree on the "no way of knowing". Pretty often, people post for karma gain on reddit/YC or their twitter account, so this is usually traceable.

**Comment by carols10cents** [comment]
We discussed in IRC that we should think about access control of things before posting them. It should not be possible to leak things that are not public, because they should be kept in private google docs or private github repos. 

Anything said in #rust-community should be considered public, but if the content linked to has access control so that it's private, then it doesn't matter if the link is posted publicly.
