### ISSUE TITLE
Friend-of-the-Forest

### ISSUE THREAD

**Issue by erickt** [rust-community/team#51]
Rust used to do Friends-of-the-Tree for significant contributions to the compiler, but now that our ecosystem has grown, how can we grow this to the broader community?

**Comment by edunham** [comment]
As discussed in the meeting, starting at http://logs.glob.uno/?c=rust-community#c3799, we have 2 related needs:

1) Core team would like Community team to select appropriate Friends Of The Tree (FOTT) for This Week In Rust (TWIR). 

2) Community team also thinks it would be cool to have a "thank you" type section in TWIR, where any Rust user/project can thank a contributor or supporter.

**Comment by brson** [comment]
I think it makes since to get started on the 'thank you' ('kudos' is a great word) section of twir first while we decide exactly what it means to be fott (or fotf - 'friend of the forest').

I strategy I suggest is to have a standing urlo thread where everyone is invited to post, and where each post is one kudo - a name, and a sentence / paragraph explaining what the've done that was awesome (with links hopefully).

That list can be rolled up every week in twir.

cc @llogiq @nasa42

**Comment by brson** [comment]
[Friend of the Tree archives](https://forge.rust-lang.org/fott.html). If we do restart fott, would be great to keep this updated.

**Comment by edunham** [comment]
cc https://github.com/rust-community/team/issues/77, nominations that @erickt collected at rustconf

**Comment by erickt** [comment]
We got this up and running!
