### ISSUE TITLE
Community Crate Naming Service

### ISSUE THREAD

**Issue by erickt** [rust-community/team#78]
I ran into some folks at RustConf that were still struggling with coming up for good names for crates since we don't have two level namespaces on crates.io. I offered that we could make a little project that helps comes up with names. @edunham suggested some options:
- markov chains
- thesaurus on project description
- ask @bstrie or the rest of the community

**Comment by booyaa** [comment]
might be a good opportunity to extend the `new` subcommand in cargo.

**Comment by erickt** [comment]
at a bare minimum, we could just create a [urlo](https://users.rust-lang.org/c/community) thread where we offer to help name things, and make sure @bstrie is watching that thread like a hawk :)

**Comment by skade** [comment]
Has this ever gone beyond "this is a charming idea"? If yes: can we move forward or close the issue?

**Comment by vigneshwerd** [comment]
+1 for the idea, I think having a subcommand in cargo to implement Markov chain procedural algorithm will be a good solution but we will have to collect some training data for that (guess we can pull this data from existing crates.io). I am interested in implementing this idea but will need some to guide me if I am struck.

**Comment by ashleygwilliams** [comment]
have we spoken to the cargo team to figure out if they would be interested in supporting such a thing? it's a cute idea but i don't think it's a good one to include in cargo itself, for several reasons, including maintenance and support burden. it turns out that keeping a markov chain from saying something really inappropriate is a Hard Problem.

classically, 'naming things' is one of the hard problems in open source. given my experience at npm i would say that a service that automagically puts potentially totally irrelevant metadata on a package would be pretty frustrating at scale. npm had more than 10x the number of packages before it got namespaces, so we shouldn't use the lack of namespaces on crates.io as a crutch, at least not prematurely. are there other package managers that offer this feature?

i have suffered this problem when naming my own packages and crates, and do have empathy for it, but a small amount of internet searching and inspiration usually is enough for me to come up with something. of all the frictions in the rust community and ecosystem, i'm not entirely sure this is one we should be turning our attention to.

**Comment by carols10cents** [comment]
Yeah, I think this could be a cargo extension if anyone wants to make it, but not part of cargo itself.

**Comment by ashleygwilliams** [comment]
i am struggling to label this issue and figure out how it fits into the community team. i am going to close, if anyone seriously disagrees, please reopen and explain. i think this is a neat idea but not likely to be an official community team project given the areas of focus that have surfaced thus far (not in stone tho, so if i am wrong please reopen and explain!)
